### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by Wayne40406130** [Wayne40406130/taiwan-native-plant-crawler#1]
- [ ] crawler MVP
  - [ ] Write script to crawl data
  - [ ] Extract necessary properties
  - [ ] Save crawled data as JSON files
  - [ ] Write a README.md to describe how to start the crawler
- [ ] Enhancement
  - [ ] Save crawled data as sqlite
  - [ ] Use docker to containerize the application
